# Login
POST http://localhost:3001/api/sessions
Content-Type: application/json

{
  "username": "alice",
  "password": "alicepsw"
}
###

# Get current session
GET http://localhost:3001/api/sessions/current
###

# Delete current session
DELETE http://localhost:3001/api/sessions/current
###

# Create new game
POST http://localhost:3001/api/games
###


# Validate game/selected path. GAME 1 Solution andrei
POST http://localhost:3001/api/games/1/validate
Content-Type: application/json

{
  "path": [12, 9, 5, 6, 4, 1, 2]
}
###


# Validate game/selected path. GAME 6 Solution alice
POST http://localhost:3001/api/games/6/validate
Content-Type: application/json

{
  "path": [12, 9, 5, 7, 3]
}
###

GET http://localhost:3001/api/games/leaderboard
###
