# Login
POST http://localhost:3001/api/sessions
Content-Type: application/json

{
  "username": "alice.russo@polito.it",
  "password": "alicepsw"
}
###

# Get current session
GET http://localhost:3001/api/sessions/current
###


# Delete current session
DELETE http://localhost:3001/api/sessions/current
###


# Get routes
GET http://localhost:3001/api/routes
###



# Create new game
POST http://localhost:3001/api/games
###



# Validate game/selected path.
POST http://localhost:3001/api/games/221/validate
Content-Type: application/json

{
  "path": [9,3,3,3]
}
###

GET http://localhost:3001/api/leaderboard
###
